### ISSUE TITLE
vars/ubuntu.yml 

### ISSUE THREAD

**Issue by AgustinBentancor** [pablodav/ansible_nagios_common_nrpe#4]
libnagios-plugin-perl is not working for Ubuntu 20.05

changed by libmonitoring-plugin-perl

https://packages.ubuntu.com/bionic/net/nagios-plugins-contrib

**Comment by pablodav** [comment]
thanks, libmonitoring-plugin-perl looks to be supported since ubuntu-16 and debian-9

https://pkgs.org/search/?q=libmonitoring-plugin-perl

So changing this to default

Adding molecule modules to test all the versions.
